# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

executors:
  xcode:
    macos:
      xcode: 11.5.0
    working_directory: /Users/distiller/project


commands:
  install_dependencies:
    description: "Install dependencies"
    steps:
      - restore_cache:
        key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
        key: 1-gems-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

jobs:
  test_pr:
    executor: xcode
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: verify_pull_request
    steps:
      - checkout
      - install_dependencies
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  run_localization_script:
    executor: xcode
    steps:
      - checkout
      - install_dependencies
      - run: ruby scripts/twn.rb
workflows:
  test_pr:
    jobs:
      - test_pr
  localization:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - twn
    jobs:
      - run_localization_script